site_name: CHIO developer documentation
theme:
  font:
    text: Roboto
  name: material
  icon:
    repo: fontawesome/brands/gitlab
  palette:
    - scheme: default
      primary: deep orange
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

copyright: Copyright &copy; 2024 German Aerospace Center (DLR)

nav:
  - Home: index.md
  - Getting started: gettingstarted.md
  - Scenarios: scenarios.md
  - About: about.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

repo_url: https://gitlab.dlr.de/ensym/lod/charging-ontology

extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.dlr.de/ensym/lod/charging-ontology
