# Test question
# Can a process have a process profile as parts?


prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix obo: <http://purl.obolibrary.org/obo/>

ask
where
{
obo:BFO_0000144 rdfs:subClassOf obo:BFO_0000003 .
}