[package]
name = "ql-heuristic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
horned-owl = { git = "https://github.com/phillord/horned-owl.git", branch = "devel" }
