name: Compile Paper
on:
    push:
      paths:
        - paper/**
        - .github/workflows/paperci.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
      - uses: actions/setup-python@v5
      - uses: ts-graphviz/setup-graphviz@v2
        with:
            distribution: "adopt"
            java-version: "11"
      - name: make
        run: |
              make
              make imports
      - name: get-dependencies
        run: |
                cp assets/catalog.xml  tmp/catalog.xml
                curl -L -o robot.jar https://github.com/ontodev/robot/releases/download/v1.9.5/robot.jar
                bash scripts/visualization/icity-extract.sh
                bash scripts/visualization/viz-transformations.sh
                bash scripts/visualization/chio-extract-viz.sh
      - name: compile-figures
        run: |
                pip install py-horned-owl pygraphviz
                python scripts/visualization/paper-diagrams.py
                python scripts/visualization/icity-diagram.py
      - uses: actions/upload-artifact@master
        with:
            name: figures
            path: |
                    tmp/*.dot
                    tmp/svg/*.svg
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: paper/paper.tex
          work_in_root_file_dir: true
          latexmk_shell_escape: true
      - name: Upload PDF file
        uses: actions/upload-artifact@master
        with:
          name: PDF
          path: paper/paper.pdf